services:
  - type: web
    name: audio-converter-bot
    runtime: python
    pythonVersion: "3.9.7"
    buildCommand: |
      pip install -r requirements.txt
      python -c "import os; open('.env', 'w').write(f'TOKEN={os.environ['TOKEN']}\nPORT=10000')"
    startCommand: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 60 app:app
    envVars:
      - key: TOKEN
        sync: false
      - key: PORT
        value: 10000
    plan: free
